# -*- coding: utf-8 -*-
"""Actividad 1 Daniela Fuentes Bello.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1BWyPEhXQyImUtEt9bgWJ_BLAXKJH5L
"""

import pandas as pd
from google.colab import files

# Subiendo el archivo CSV
uploaded = files.upload()

# Cargando el archivo
file_name = 'LISTADO_DE_PREDIDOS_MUNICIPIO_DE_BOYACA-BOYACA_20240803.csv'

# Cargar el archivo CSV
df = pd.read_csv(file_name)


# Descartar valores nulos
df_clean = df.dropna()

# Convertir las columnas 'Codigo', 'Avaluo', 'Predial' a valores numéricos
df_clean['Codigo'] = pd.to_numeric(df_clean['Codigo'], errors='coerce')
df_clean['Avaluo'] = pd.to_numeric(df_clean['Avaluo'], errors='coerce')
df_clean['Predial'] = pd.to_numeric(df_clean['Predial'], errors='coerce')

# Descartar filas que se convirtieron a NaN debido a errores en la conversión
df_clean = df_clean.dropna()

# Asignar valor numerico a las direcciones
df_clean.sort_values('Dirección', inplace=True)
df_clean['Numero_Dirección'] = (df_clean['Dirección'] != df_clean['Dirección'].shift()).cumsum()

# Descartar la columna 'Predial' por información innecesaria y direccion
df_clean = df_clean.drop(columns=['Predial'])
df_clean = df_clean.drop(columns=['Dirección'])

# Calcular el impuesto predial (0.5% del avaluó)
df_clean['Impuesto_Predial'] = df_clean['Avaluo'] * 0.005

# Mostrar todas las filas del DataFrame limpio
print("\nTodas las filas del DataFrame limpio:")
print(df_clean)

# Guardar el DataFrame limpio en un nuevo archivo CSV
clean_file_name = 'LISTADO_DE_PREDIDOS_MUNICIPIO_DE_BOYACA-BOYACA_20240803_clean.csv'
df_clean.to_csv(clean_file_name, index=False)

# Descargar el archivo limpio a tu sistema local
files.download(clean_file_name)

